apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 1m
  timeout: 2m
  maxHistory: 2
  chart:
    spec:
      interval: 1m
      chart: podinfo
      ## https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/Chart.yaml#L2
      version: "6.3.3"
      sourceRef:
        kind: HelmRepository
        name: podinfo
      reconcileStrategy: Revision
  values:
    ## https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml

    replicaCount: 1
    backends:
      - http://podinfo.podinfo:9898/echo

    image:
      tag: 6.3.0

    ui:
      ## blue
      color: "#4078c0"

    hpa:
      enabled: false

    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 256Mi
