apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-certs
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-base
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: ./frontend/istio-certs
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
