apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: latest
  timeout: 60s
  url: oci://localhost:5000/flux-system
