apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-discovery
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-base
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: ./common/istio-discovery
  prune: true
