apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
  - metallb-config.yaml
  - istio-base.yaml
  - istio-discovery.yaml
  - istio-eastwestgateway.yaml
  - istio-ingressgateway.yaml
