apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
secretGenerator:
  - name: cacerts
    files:
      - files/ca-cert.pem
      - files/ca-key.pem
      - ../../common/istio-certs/files/root-cert.pem
      - files/cert-chain.pem
generatorOptions:
  disableNameSuffixHash: true
