apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install.yaml
patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: source-controller
    path: patch_registry_proxy.yaml
  - target:
      version: v1
      kind: Deployment
      name: helm-controller
    path: patch_registry_proxy.yaml
