apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/manifests/install?ref=v0.39.0
patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: source-controller
    path: patch_registry_proxy.yaml
  - target:
      version: v1
      kind: Deployment
      name: helm-controller
    path: patch_registry_proxy.yaml
