apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-eastwestgateway
spec:
  interval: 1m
  timeout: 2m
  maxHistory: 2
  chart:
    spec:
      interval: 1m
      chart: gateway
      ## https://istio-release.storage.googleapis.com/charts/index.yaml
      ## https://github.com/istio/istio/releases
      version: "1.17.0"
      sourceRef:
        kind: HelmRepository
        name: istio
      reconcileStrategy: Revision
  values:
    ## https://github.com/istio/istio/blob/master/manifests/charts/gateway/values.yaml
    service:
      loadBalancerIP: ${lb_ip_istio_eastwestgateway}
      ports:
        - name: status-port
          port: 15021
          targetPort: 15021
        - name: tls
          port: 15443
          targetPort: 15443
        - name: tls-istiod
          port: 15012
          targetPort: 15012
        - name: tls-webhook
          port: 15017
          targetPort: 15017
    networkGateway: ${cluster_name}
