apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 1m
  timeout: 2m
  maxHistory: 2
  chart:
    spec:
      interval: 1m
      chart: base
      ## https://istio-release.storage.googleapis.com/charts/index.yaml
      ## https://github.com/istio/istio/releases
      version: "1.17.0"
      sourceRef:
        kind: HelmRepository
        name: istio
      reconcileStrategy: Revision
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    ## https://github.com/istio/istio/blob/master/manifests/charts/base/values.yaml
